#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0" )" >/dev/null 2>&1 ; pwd -P )"

echo "This program only works on MacOS"
echo "Please make sure you have vscode installed."

echo "Export KTHOME=$SCRIPTPATH"
echo "export KTHOME=$SCRIPTPATH" >> ~/.bashrc

echo "Add KT to PATH"
echo "export PATH=\$PATH:$SCRIPTPATH/bin" >> ~/.bashrc

echo "source $SCRIPTPATH/kalias/kaliasrc" >> ~/.bashrc
